### ISSUE TITLE
Another crash on sync

### ISSUE THREAD

**Issue by xiaomi7732** [xiaomi7732/CodeWithSaar#24]
---------------------------
Error invoking SyncCommand
---------------------------
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)

   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)

   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)

   at System.Guid.Parse(String input)

   at CodeNameK.DAL.PathProviderBase.GetDataPointInfo(String path, Func`2 decodeCategoryName) in D:\Repos\CodeWithSaar\CodeNameK\src\CodeNameK.DataAccess\PathProviderBase.cs:line 86

   at CodeNameK.DAL.PathProviderBase.TryGetDataPointInfo(String path, DataPointPathInfo& pathInfo) in D:\Repos\CodeWithSaar\CodeNameK\src\CodeNameK.DataAccess\PathProviderBase.cs:line 39

   at CodeNameK.DAL.LocalPathProvider.ListAllDataPointPaths()+MoveNext() in D:\Repos\CodeWithSaar\CodeNameK\src\CodeNameK.DataAccess\LocalPathProvider.cs:line 42

   at System.Linq.Enumerable.ExceptIterator[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)+MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at CodeNameK.DAL.OneDrive.OneDriveSync.UpSyncAsync(IEnumerable`1 source, IProgress`1 progress, CancellationToken cancellationToken)+MoveNext() in D:\Repos\CodeWithSaar\CodeNameK\src\CodeNameK.DataAccess\OneDrive\OneDriveSync.cs:line 133

   at CodeNameK.DAL.OneDrive.OneDriveSync.UpSyncAsync(IEnumerable`1 source, IProgress`1 progress, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

   at CodeNameK.BIZ.BizSync.Sync(IProgress`1 progress, CancellationToken cancellationToken) in D:\Repos\CodeWithSaar\CodeNameK\src\CodeNameK.Biz\BizSync.cs:line 244

   at CodeNameK.BIZ.BizSync.Sync(IProgress`1 progress, CancellationToken cancellationToken) in D:\Repos\CodeWithSaar\CodeNameK\src\CodeNameK.Biz\BizSync.cs:line 244

   at CodeNameK.ViewModels.MainViewModel.SyncImpAsync(Object parameters) in D:\Repos\CodeWithSaar\CodeNameK\src\CodeNameK.ViewModels\MainViewModel.cs:line 487

   at CodeNameK.Core.Utilities.TaskUtilities.FireWithExceptionHandler(Task task, Action`1 exceptionHandler) in D:\Repos\CodeWithSaar\CodeNameK\src\CodeNameK.Contracts\Utilities\TaskUtilities.cs:line 26
---------------------------
OK   
---------------------------

**Comment by xiaomi7732** [comment]
This is caused by noisy files from the old app. The file location is a break change. Fix available.
